global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hybrid-infrastructure'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Flask application
  - job_name: 'flask-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask-app:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+).*'
        replacement: '${1}'

  # Docker containers (requires cAdvisor)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # Node exporter for system metrics (optional)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # PostgreSQL exporter (optional)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis exporter (optional)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
